10 blog/blog/core/views.py
from flask import render_template, request, Blueprint
from blog.models import BlogPost

core = Blueprint("core", __name__)


@core.route("/")
def index():
    page = request.args.get("page", 1, type=int)
    blog_posts = BlogPost.query.order_by(BlogPost.date.desc()).paginate(
        page=page, per_page=10
    )
    return render_template("index.html", blog_posts=blog_posts)


@core.route("/info")
def info():
    return render_template("info.html")

10 blog/blog/posts/views.py
from flask import render_template, url_for, redirect, request, Blueprint, flash, abort
from flask_login import current_user, login_required
from blog import db
from blog.models import BlogPost
from blog.posts.forms import BlogPostForm

blog_posts = Blueprint("blog_posts", __name__)

# Create post
@blog_posts.route("/create", methods=["GET", "POST"])
@login_required
def create_post():
    form = BlogPostForm()
    if form.validate_on_submit():
        blog_post = BlogPost(
            title=form.title.data, text=form.text.data, user_id=current_user.id
        )
        db.session.add(blog_post)
        db.session.commit()
        flash("Post Created!")
        return redirect(url_for("core.index"))
    return render_template("create_post.html", form=form)


# View post
@blog_posts.route("/<int:blog_post_id>")
def blog_post(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    return render_template(
        "blog_post.html", title=blog_post.title, date=blog_post.date, post=blog_post
    )


# Update
@blog_posts.route("/<int:blog_post_id>/update", methods=["GET", "POST"])
@login_required
def update(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    if blog_post.author != current_user:
        abort(403)

    form = BlogPostForm()
    if form.validate_on_submit():
        blog_post.title = form.title.data
        blog_post.text = form.text.data
        db.session.commit()
        flash("Post Updated!")
        return redirect(url_for("blog_posts.blog_post", blog_post_id=blog_post_id))

    elif request.method == "GET":
        form.title.data = blog_post.title
        form.text.data = blog_post.text

    return render_template("create_post.html", title="Updating", form=form)


# Delete
@blog_posts.route("/<int:blog_post_id>/delete", methods=["GET", "POST"])
@login_required
def delete_post(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    if blog_post.author != current_user:
        abort(403)

    db.session.delete(blog_post)
    db.session.commit()
    flash("Post Deleted!")
    return redirect(url_for("core.index"))

10 blog/blog/users/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from blog import db
from blog.models import User, BlogPost
from blog.users.forms import LoginForm, RegistrationForm, UpdateUserForm
from blog.users.picture_handler import add_profile_picture

users = Blueprint("users", __name__)

# register
@users.route("/register", methods=["GET", "POST"])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(
            email=form.email.data,
            username=form.username.data,
            password=form.password.data,
        )
        db.session.add(user)
        db.session.commit()
        flash("Thank you for registering! Welcome aboard!")
        return redirect(url_for("users.login"))
    return render_template("register.html", form=form)


# login
@users.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user.check_password(form.password.data) and user is not None:
            login_user(user)
            flash("You're now signed in!")

            next = request.args.get("next")

            if next == None or not next[0] == "/":
                next = url_for("core.index")

            return redirect(next)
    return render_template("login.html", form=form)


# logout
@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("core.index"))


# account
@users.route("/account", methods=["GET", "POST"])
@login_required
def account():
    form = UpdateUserForm()
    if form.validate_on_submit():
        if form.picture.data:
            username = current_user.username
            pic = add_profile_picture(form.picture.data, username)
            current_user.profile_image = pic
        current_user.username = form.username.data
        db.session.commit()
        flash("User Profile Updated!")
        return redirect(url_for("users.account"))
    elif request.method == "GET":
        form.username.data = current_user.username
        form.email.data = current_user.email
    profile_image = url_for(
        "static", filename="profile/pics" + current_user.profile_image
    )
    return render_template("account.html", profile_image=profile_image, form=form)


# Users posts
@users.route("/<username>")
def user_posts(username):
    page = request.args.get("page", 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    blog_posts = (
        BlogPost.query.filter_by(author=user)
        .order_by(BlogPost.date.desc())
        .paginate(page=page, per_page=5)
    )
    return render_template("user_blog_posts.html", blog_posts=blog_posts, user=user)

10 blog/blog/templates/account.html
{% extends 'base.html' %}

{% block content %}
<div class="p-5 mb-4 bg-light rounded-3">
    <div class="container-fluid py-5" align="center">
        <h1 class="display-5 fw-bold">Welcome {{current_user.username}}!</h1>
        <img src="{{ url_for('static', filename='profile_pics/' + current_user.profile_image) }}" alt="##">
        <form method="POST" action="" enctype="multipart/form-data">
            <br>
            {{ form.hidden_tag() }}
            <div class="mb-2 row">
                {{ form.email.label(class='col-sm-5 col-form-group') }}
                <div class="col-sm-5">
                    {{ form.email(class='form-control') }}
                </div>
            </div>
            <div class="mb-3 row">
                {{ form.username.label(class='col-sm-5 col-form-label') }}
                <div class="col-sm-5">
                    {{ form.username(class='form-control') }}
                </div>
            </div>
            <div class="mb-3 row">
                {{ form.picture.label(class='col-sm-5') }}
                <div class="col-sm-4">
                    {{ form.picture }}
                </div>
            </div>
            {{ form.submit(class="btn btn-primary") }}
        </form>
    </div>
</div>

{% endblock %}

10 blog/blog/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"
    integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js"
    integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/"
    crossorigin="anonymous"></script>
  <title>Blog</title>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">
        <img src="../static/pupper.png" alt="##" width="35" height="35">
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('core.index')}}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('core.info')}}">About</a>
          </li>
          {% if current_user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('users.account')}}">Account</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('blog_posts.create_post')}}">Create Post</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('users.logout')}}">Log Out</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('users.login')}}">Log In</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('users.register')}}">Register</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
  <div class='container'>
    {% block content %}
    {% endblock %}
  </div>
</body>

</html>

10 blog/blog/templates/blog_post.html
{% extends 'base.html' %}

{% block content %}
<div class="p-5 mb-4 bg-light rounded-3">
    <div class="container-fluid py-5">
        <h1 class="display-5 fw-bold">{{post.title}}</h1>
        <h2 class="display-5 fw-bold">Posted by {{post.author.name}}</h2>
        <h3 class="display-5 fw-bold">Published at {{post.date.strftime('%B %d, %Y')}}</h3>
        <p>{{post.text}}</p>
        {% if post.author == current_user %}
        <div>
            <a href="{{url_for('blog_posts.update',blog_post_id=post.id)}}" class="btn btn-primary">Update</a>
            <button type="button" class="btn btn-danger" data-bs-toggle='modal'
                data-bs-target="#del_modal">Delete</button>
        </div>
        {% endif %}
    </div>
</div>

<div class="modal fade" tabindex="-1" role="dialog" id="del_modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Delete Post</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete the post?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <form action="{{url_for('blog_posts.delete_post',blog_post_id=post.id)}}" method="post">
                    <input class="btn btn-danger" type="submit" value="Delete">
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

10 blog/blog/templates/create_post.html
{% extends 'base.html' %}

{% block content %}
<div class="p-5 mb-4 bg-light rounded-3">
    <div class="container-fluid py-5">
        <h1 class="display-5 fw-bold">Sign in!</h1>
        <br>
        <form method="POST">
            {{ form.hidden_tag() }}
            <div class="form-group">
                {{ form.title.label(class='col-sm-2 form-control-label') }}
                <!-- <div class="col-sm-5"> -->
                {{ form.title(class='form-control form-control-lg') }}
            </div>
            <div class="form-group">
                {{ form.text.label(class='col-sm-2 form-control-label') }}
                {{ form.text(class='form-control form-control-lg') }}
            </div>
            <div class="form-group">
                {{ form.submit(class='btn btn-outline-info') }}
            </div>
        </form>
    </div>
</div>
{% endblock %}

10 blog/blog/templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="p-5 mb-4 bg-light rounded-3">
    <div class="container-fluid py-5">
        <h1 class="display-5 fw-bold">Welcome to a random blog posting site!</h1>
        <!-- <p class="col-md-8 fs-4">Using a series of utilities, you can create this jumbotron, just like the one in
            previous versions of Bootstrap. Check out the examples below for how you can remix and restyle it to your
            liking.</p>
        <button class="btn btn-primary btn-lg" type="button">Example button</button> -->
    </div>
</div>
<div class="container">
    {% for post in blog_posts.items %}
    <div class="card">
        <div class="card-body">
            <h2>
                <a href="{{url_for('blog_posts.blog_post',blog_post_id=post.id)}}" class="card-title">{{post.title}}</a>
            </h2>
            <a href="{{url_for('users.user_posts',username=post.author.username)}}">Written by:
                {{post.author.username}}</a>
            <p>Published on {{post.date.strftime("%Y-%m-%d")}}</p>
            <p class="card-text">{{ post.text[:100] }}...</p>
            <a href="{{url_for('blog_posts.blog_post',blog_post_id=post.id)}}" class="btn btn-primary">Read Post</a>
        </div>
    </div>
    {% endfor %}
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            {% for page_num in blog_posts.iter_pages(left_edge=1, right_edge=1, left_current=1,right_current=2) %}
            {% if blog_posts.page == page_num %}
            <li class="page-item active">
                <a href="#" class="page-link">{{page_num}}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a href="{{url_for('core.index', page=page_num)}}" class="page-link">{{page_num}}</a>
            </li>
            {% endif %}
            {% endfor %}
        </ul>
    </nav>
</div>
{% endblock %}

10 blog/blog/templates/info.html
{% extends 'base.html' %}

{% block content %}
<div class="p-5 mb-4 bg-light rounded-3">
    <div class="container-fluid py-5">
        <h1 class="display-5 fw-bold">About Us</h1>
        <p class="col-md-8 fs-4">Using a series of utilities, you can create this jumbotron, just like the one in previous versions of Bootstrap. Check out the examples below for how you can remix and restyle it to your liking.</p>
        <button class="btn btn-primary btn-lg" type="button">Example button</button>
    </div>
</div>
{% endblock %}

10 blog/blog/templates/login.html
{% extends 'base.html' %}

{% block content %}
<div class="p-5 mb-4 bg-light rounded-3">
    <div class="container-fluid py-5">
        <h1 class="display-5 fw-bold">Sign in!</h1>
        <br>
        <form method="POST">
            {{ form.hidden_tag() }}
            <div class="mb-2 row">
                {{ form.email.label(class='col-sm-2 col-form-label') }}
                <div class="col-sm-5">
                    {{ form.email(class='form-control') }}
                </div>
            </div>
            <div class="mb-2 row">
                {{ form.password.label(class='col-sm-2 col-form-label') }}
                <div class="col-sm-5">
                    {{ form.password(class='form-control') }}
                </div>
            </div>
            {{ form.submit(class="btn btn-primary") }}
        </form>
    </div>
</div>
{% endblock %}

10 blog/blog/templates/register.html
{% extends 'base.html' %}

{% block content %}
<div class="p-5 mb-4 bg-light rounded-3">
    <div class="container-fluid py-5">
        <h1 class="display-5 fw-bold">Register your account!</h1>
        <br>
        <form method="POST">
            {{ form.hidden_tag() }}
            <div class="mb-2 row">
                {{ form.email.label(class='col-sm-2 col-form-label') }}
                <div class="col-sm-5">
                    {{ form.email(class='form-control') }}
                </div>
            </div>
            <div class="mb-2 row">
                {{ form.username.label(class='col-sm-2 col-form-label') }}
                <div class="col-sm-5">
                    {{ form.username(class='form-control') }}
                </div>
            </div>
            <div class="mb-2 row">
                {{ form.password.label(class='col-sm-2 col-form-label') }}
                <div class="col-sm-5">
                    {{ form.password(class='form-control') }}
                </div>
            </div>
            <div class="mb-2 row">
                {{ form.pass_confirm.label(class='col-sm-2 col-form-label') }}
                <div class="col-sm-5">
                    {{ form.pass_confirm(class='form-control') }}
                </div>
            </div>
            {{ form.submit(class="btn btn-primary") }}

        </form>
    </div>
</div>
{% endblock %}

10 blog/blog/templates/user_blog_posts.html
{% extends 'base.html' %}

{% block content %}
<div class="p-5 mb-4 bg-light rounded-3">
    <div class="container-fluid py-5">
        <h1 class="display-5 fw-bold">{{current_user.username}}</h1>
        <img src="{{url_for('static', filename='profile_pics/'+user.profile_image)}}" alt="##">
    </div>
</div>

{% for post in blog_posts.items %}
<div class="card">
    <div class="card-body">
        <h2><a href="{{url_for('blog_posts.blog_post',blog_post_id=post.id)}}" class='card-title'>{{post.title}}</a>
        </h2>
        Written by: <a
            href="{{url_for('users.user_posts', username=post.author.username)}}">{{post.author.username}}</a>
        <p class="text-muted">Published on: {{post.date.strftime("%Y-%m-%d")}}</p>
        <br>
        <p>{{post.text}}</p>
        <br>
    </div>
</div>
{% endfor %}


<nav aria-label="userpage">
    <ul class="pagination justify-content-center">
        {% for page_num in blog_posts.iter_pages(left_edge=1, right_edge=1, left_current=1,right_current=2) %}
        {% if blog_posts.page == page_num %}
        <li class="page-item disabled">
            <a href="#" class="page-link">{{page_num}}</a>
        </li>
        {% else %}
        <li class="page-item">
            <a href="{{url_for('users.user_posts',username=user.username, page=page_num)}}"
                class="page-link">{{page_num}}</a>
        </li>
        {% endif %}
        {% endfor %}
    </ul>
</nav>

{% endblock %}