08 restructuring/myproject/models.py
from myproject import db

## Puppies table
class Puppy(db.Model):
    __tablename__ = 'puppies'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.Text)
    owner = db.relationship('Owner',backref="puppy",uselist=False)
    
    def __init__(self,name):
        self.name = name
    
    def __repr__(self):
        if self.owner:
            return f"{self.name} with an ID of {self.id} has been adopted by {self.owner.name}"
        else:
            return f"{self.name} with an ID of {self.id} has not been adopted yet! :( "

## Owners table
class Owner(db.Model):
    __tablename__ = "owners"
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.Text)
    puppy_id = db.Column(db.Integer,db.ForeignKey("puppies.id"))

    def __init__(self,name,puppy_id):
        self.name = name
        self.puppy_id = puppy_id

08 restructuring/myproject/owners/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SubmitField

class AddForm(FlaskForm):
    id = IntegerField("What's the ID of the pupper?&#160")
    name = StringField("What's the name of the owner?&#160")
    submit = SubmitField("Add owner!")

08 restructuring/myproject/puppies/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SubmitField

class AddForm(FlaskForm):
    name = StringField("What's the name of the pupper?&#160")
    submit = SubmitField("Add pupper!")

class DelForm(FlaskForm):
    id = IntegerField("What's the ID of the pupper?&#160")
    submit = SubmitField("Remove pupper!")

08 restructuring/myproject/__init__.py
# Importing libraries
import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

# Initializing flask app
app = Flask(__name__)
# SECRET_KEY is specified directly temporarily
app.config["SECRET_KEY"] = "placeholder_key"

# Setting base directory and SQLite Database
basedir = os.path.abspath(os.path.dirname(__file__))
app.config["SQLALCHEMY_DATABASE_URI"] = 'sqlite:///'+os.path.join(basedir,'data.sqlite')
app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False

db = SQLAlchemy(app)
Migrate(app,db)

from myproject.puppies.views import puppies_blueprint
from myproject.owners.views import owners_blueprint

app.register_blueprint(owners_blueprint,url_prefix='/owners')
app.register_blueprint(puppies_blueprint,url_prefix='/puppies')

08 restructuring/myproject/owners/views.py
from flask import Blueprint, render_template, redirect, url_for
from myproject import db
from myproject.models import Owner
from myproject.owners.forms import AddForm

owners_blueprint = Blueprint("owners",__name__, template_folder='templates/owners')

@owners_blueprint.route("/add",methods=['GET', 'POST'])
def add_owner():
    form = AddForm()
    if form.validate_on_submit():
        id = form.id.data
        name = form.name.data
        add_owner = Owner(name,id)
        db.session.add(add_owner)
        db.session.commit()
        return redirect(url_for('owners.add_owner'))
    return render_template('owner.html',form=form)

08 restructuring/myproject/puppies/views.py
from flask import Blueprint, render_template, redirect, url_for
from myproject import db
from myproject.models import Puppy
from myproject.puppies.forms import AddForm, DelForm

puppies_blueprint = Blueprint('puppies',__name__,template_folder='templates/puppies')

@puppies_blueprint.route("/add",methods=['GET', 'POST'])
def add_pup():
    form = AddForm()
    if form.validate_on_submit():
        name = form.name.data
        new_pupper = Puppy(name)
        db.session.add(new_pupper)
        db.session.commit()
        return redirect(url_for('puppies.add_pup'))
    return render_template('add.html', form=form)

@puppies_blueprint.route("/delete",methods=['GET', 'POST'])
def del_pup():
    form = DelForm()
    if form.validate_on_submit():
        id = form.id.data
        del_pupper = Puppy.query.get(id)
        db.session.delete(del_pupper)
        db.session.commit()
        return redirect(url_for('puppies.del_pup'))
    return render_template('delete.html', form=form)

@puppies_blueprint.route("/list")
def list_pup():
    puppies = Puppy.query.all()
    return render_template('list.html', puppies=puppies)

08 restructuring/myproject/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
    <title>Pupper Adoption Page</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{{url_for('index')}}">
            <img src="../static/pupper.png" width='40' height='40' class="d-inline-block align-top">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
            <a class="nav-link" href="{{url_for('puppies.add_pup')}}">Add Puppers</a>
            <a class="nav-link" href="{{url_for('puppies.del_pup')}}">Remove Puppers</a>
            <a class="nav-link" href="{{url_for('owners.add_owner')}}">Add Owners</a>
            <a class="nav-link" href="{{url_for('puppies.list_pup')}}">List Puppers</a>
            </div>
        </div>
    </nav>
    {% block content %}
    {% endblock %}
</body>
</html>

08 restructuring/myproject/templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class='jumbotron'>
    <h1>Welcome to the Pupper Adoption Agency!</h1>
    <p>You can do the following here:</p>
    <ul>
        <li>You can put your puppers up for adoption!</li>
        <li>You can remove the puppers that have been adopted!</li>
    </ul>
</div>
{% endblock %}